### ISSUE TITLE
SmartPtr enhancements

### ISSUE THREAD

**Issue by GbaLog** [aragajaga/panitent#1]
hello.

1. 
https://github.com/Aragajaga/panitent/blob/70b1018278a1967ba97524f8cc7299ff550682fa/src/smartptr.h#L4-L7  
i think it'd be better to create concrete structure or pointer-to-structure for smart pointer.  
especially since you create a concrete structure in the implementation anyway:  
https://github.com/Aragajaga/panitent/blob/70b1018278a1967ba97524f8cc7299ff550682fa/src/smartptr.c#L4-L8  
  
2. name `smartptr` doesn't reflect the smartness of the pointer.  
since you implemented reference counter pointer, you can name it `refcnt_ptr`. what is much clearer than just `smart_ptr`.

**Comment by Philosoph228** [comment]
Hi! Thank you for your contribution. If I right understood you, the parameters of type `void*` and private structure definition are made for data protection. No one file beside should access this structure directly.
I see there possible improvement to define another data type based on `void*`.

About naming, yes, you right. When I wrote this I didn't thought much about it. I'll consider to rename it for something like you suggest, maybe `refcptr_t` would be a good option too.

**Comment by Philosoph228** [comment]
Check e385fb9

**Comment by GbaLog** [comment]
@Philosoph228 hello.  
> If I right understood you, the parameters of type void* and private structure definition are made for data protection. No one file beside should access this structure directly.  
  
yes, but i didn't propose to expose internals, i proposed exposing name with forwarding declaration.  
something like this:  
```c
//.h
typedef struct refcnt_ptr refcnt_ptr_t;
//.c
struct refcnt_ptr
{
  //...
};
```  
your variant also fits for this idiom, but it has some pitfalls.  
for example, API of your smart pointer now is:  
https://github.com/Aragajaga/panitent/blob/0eed94508b8756b32e73aecca6f85967d6054168/src/crefptr.h#L6-L9  
i think `crefptr_get` return type should be `void *`, because it returns internal pointer, not `crefptr_t`.   
and arguments of `crefptr_new` should also take `void *`.  
this is why i prefer variant with typedef on struct. with it you would have gotten compilation errors.  
  
also i noticed that there's no function `crefptr_ref` to increase ref counter.
